params:
  seed: 42

  # environment wrapper clipping
  env:
    clip_actions: 1.0

  algo:
    name: pmp4setsip_continuous

  model:
    name: continuous_pmp4setsip

  network:
    name: pmp4setsip
    separate: True

    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: -2.9
        fixed_sigma: True
        learn_sigma: False
    mlp:
      units: [1024, 512]
      activation: elu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

    disc:
      units: [1024, 512]
      activation: relu

      initializer:
        name: default

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load

  config:
    name: humanoid_direct
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: -1  # configured from the script (based on num_envs)
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-5
    lr_schedule: adaptive
    kl_threshold: 0.008
    score_to_win: 20000
    max_epochs: 10000
    save_best_after: 100
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: False
    e_clip: 0.2
    horizon_length: 16
    minibatch_size: 16384
    mini_epochs: 6
    critic_coef: 5
    clip_value: False
    seq_len: 4
    bounds_loss_coef: 10
    # amp
    pmp4setsip_obs_demo_buffer_size: 200000
    pmp4setsip_replay_buffer_size: 500000
    pmp4setsip_replay_keep_prob: 0.01
    pmp4setsip_batch_size: 512
    pmp4setsip_minibatch_size: 4096
    disc_coef: 5
    disc_logit_reg: 0.05
    disc_grad_penalty: 5
    disc_reward_scale: 2
    disc_weight_decay: 0.0001
    normalize_pmp4setsip_input: True

    numAMPObsSteps: 8
    numEnvs: 1024

    task_reward_w: 0.5
    disc_reward_w: 0.5

    disc_motion_reference_reward_w: 0.9
    disc_interactive_prior_reward_w: 0.1
