# Copyright (c) 2022-2024, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Configuration for the Mujoco Humanoid robot."""

from __future__ import annotations

import omni.isaac.lab.sim as sim_utils
from omni.isaac.lab.actuators import ImplicitActuatorCfg
from omni.isaac.lab.assets import ArticulationCfg
from omni.isaac.lab.utils.assets import LOCAL_ASSET_ROOT_DIR

##
# Configuration
##
HUMANOID_WITH_HANDS_CFG = ArticulationCfg(
    prim_path="{ENV_REGEX_NS}/Robot",
    spawn=sim_utils.UsdFileCfg(
        usd_path=f"{LOCAL_ASSET_ROOT_DIR}/Robots/ViRVIG/amp_humanoid_MPL_hands.usd",
        # rigid_props=sim_utils.RigidBodyPropertiesCfg(
        #     disable_gravity=None,
        #     max_depenetration_velocity=10.0,
        #     enable_gyroscopic_forces=True,
        # ),
        # articulation_props=sim_utils.ArticulationRootPropertiesCfg(
        #     enabled_self_collisions=True,
        #     solver_position_iteration_count=4,
        #     solver_velocity_iteration_count=0,
        #     sleep_threshold=0.005,
        #     stabilization_threshold=0.001,
        # ),
        # copy_from_source=False,
    ),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, 1.34),
        joint_pos={".*": 0.0},
    ),
    # TODO: actuators check
    actuators={
        "body": ImplicitActuatorCfg(
            joint_names_expr=[
                "abdomen_.*",
                "neck_.*",
                "right_shoulder_.*",
                "right_elbow_.*",
                "left_shoulder_.*",
                "left_elbow_.*",
                "right_hip_.*",
                "right_knee",
                "right_ankle_.*",
                "left_hip_.*",
                "left_knee",
                "left_ankle_.*",
                "right_thumb_MCP",
                "right_index_MCP",
                "right_middle_MCP",
                "right_ring_MCP",
                "right_pinky_MCP",
                "right_wrist_.*",
                "right_thumb_ABD",
                "right_thumb_PIP",
                "right_thumb_DIP",
                "right_index_ABD",
                # "right_ring_ABD",
                "right_pinky_ABD",
                "left_thumb_MCP",
                "left_index_MCP",
                "left_middle_MCP",
                "left_ring_MCP",
                "left_pinky_MCP",
                "left_wrist_.*",
                "left_thumb_ABD",
                "left_thumb_PIP",
                "left_thumb_DIP",
                "left_index_ABD",
                # "left_ring_ABD",
                "left_pinky_ABD",
                ],
            stiffness={
                "abdomen_.*": 1000.0,
                "neck_.*": 100.0,
                "right_shoulder_.*": 400.0,
                "right_elbow_.*": 300.0,
                "left_shoulder_.*": 400.0,
                "left_elbow_.*": 300.0,
                "right_hip_.*": 500.0,
                "right_knee": 500.0,
                "right_ankle_.*": 400.0,
                "left_hip_.*": 500.0,
                "left_knee": 500.0,
                "left_ankle_.*": 400.0,
                "right_thumb_MCP": 100.0,
                "right_index_MCP": 100.0,
                "right_middle_MCP": 100.0,
                "right_ring_MCP": 100.0,
                "right_pinky_MCP": 100.0,
                "right_wrist_.*": 100.0,
                "right_thumb_ABD": 100.0,
                "right_thumb_PIP": 100.0,
                "right_thumb_DIP": 100.0,
                "right_index_ABD": 100.0,
                # "right_ring_ABD": 100.0,
                "right_pinky_ABD": 100.0,
                "left_thumb_MCP": 100.0,
                "left_index_MCP": 100.0,
                "left_middle_MCP": 100.0,
                "left_ring_MCP": 100.0,
                "left_pinky_MCP": 100.0,
                "left_wrist_.*": 100.0,
                "left_thumb_ABD": 100.0,
                "left_thumb_PIP": 100.0,
                "left_thumb_DIP": 100.0,
                "left_index_ABD": 100.0,
                # "left_ring_ABD": 100.0,
                "left_pinky_ABD": 100.0,
            },
            damping={
                "abdomen_.*": 100.0,
                "neck_.*": 10.0,
                "right_shoulder_.*": 40.0,
                "right_elbow_.*": 30.0,
                "left_shoulder_.*": 40.0,
                "left_elbow_.*": 30.0,
                "right_hip_.*": 50.0,
                "right_knee": 50.0,
                "right_ankle_.*": 40.0,
                "left_hip_.*": 50.0,
                "left_knee": 50.0,
                "left_ankle_.*": 40.0,
                "right_thumb_MCP": 4.0,
                "right_index_MCP": 4.0,
                "right_middle_MCP": 4.0,
                "right_ring_MCP": 4.0,
                "right_pinky_MCP": 4.0,
                "right_wrist_.*": 10.0,
                "right_thumb_ABD": 4.0,
                "right_thumb_PIP": 4.0,
                "right_thumb_DIP": 4.0,
                "right_index_ABD": 4.0,
                # "right_ring_ABD": 4.0,
                "right_pinky_ABD": 4.0,
                "left_thumb_MCP": 4.0,
                "left_index_MCP": 4.0,
                "left_middle_MCP": 4.0,
                "left_ring_MCP": 4.0,
                "left_pinky_MCP": 4.0,
                "left_wrist_.*": 10.0,
                "left_thumb_ABD": 4.0,
                "left_thumb_PIP": 4.0,
                "left_thumb_DIP": 4.0,
                "left_index_ABD": 4.0,
                # "left_ring_ABD": 4.0,
                "left_pinky_ABD": 4.0,
            },
        ),
    },
)
"""Configuration for the Mujoco Humanoid robot with MPL Hands."""
